# CircleCI config file for Python
version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.5

        working_directory: ~/repo

        steps:
            # Step 1 obtain code from github
            - checkout
            # Step 2 create virtual env and install deps.
            - run:
                name: install dependencies
                command: |
                   python3 -m venv venv
                   . venv/bin/activate
                   pip install -r requirements.txt
            # Step 3 rutn linter and unit tests
            - run:
                name: run tests
                command: |
                    . venv/bin/activate
                    flake8 --exclude=venv* --statistics
                    pytest -v --cov=math_library
